### ISSUE TITLE
Builder pattern preparation data structs

### ISSUE THREAD

**Issue by ersin-ertan** [konmik/solid#12]
Was reading [autovalue builders collections](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#collection), and tried using a List in the Builder to populate my SolidList<String>, then read [Solid Collections > Details](https://github.com/konmik/solid#details), so I switched the Builder's List to ArrayList, but got the error message: 
```Error:(25, 33) error: Parameter type of setter method should be solid.collections.SolidList<java.lang.String> to match getter com.test.autovalue.Element.names```

```java
@AutoValue
abstract class Element {

    public abstract SolidList<String> names();

    public static Builder builder(){
        return new AutoValue_Element.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder{
//        public abstract Builder names(SolidList<String> value); // works
        public abstract Builder names(ArrayList<String> value); // doesn't
        public abstract Element build();
    }
}
```

**Comment by konmik** [comment]
This is probably because AutoValue knows about Guava collections. I don't know if it is possible to do for Solid with an AutoValue extension, but I suspect that it will be a waste of time, the improvement is so small it simply doesn't worth it. This feature also breaks logic a little bit from my point of view, because it assumes that AutoValue knows too much about used data types.
