### ISSUE TITLE
No continuous integration

### ISSUE THREAD

**Issue by karlicoss** [konmik/solid#7]
Hey I noticed you don't run builds on Travis or any other kind of CI (I might be missing something though). I feel like we should fix that, I would be happy to help!

Also, is there any particular reason you run instrumented unit tests (which work on device/emulator) rather than plain Junit/Robolectric tests?

**Comment by konmik** [comment]
Hi, Thanks for your offer. I never had experience with Travis so this could be an interesting experiment. But why would I want it?

Sure, there is are very good reasons for running instrumentation tests:
- Pure JUnit is not enough because I need to test Parcelable.
- Robolectric does not replicate all functions correctly, so I get troubles more often than help. Tests pass, I release, and then I get bugs on real devices. This makes writing tests useless.
